/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shazamm;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author nomnelle
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    public ImageIcon loadImage(String filename) {
        System.out.println(filename);
        ImageIcon image = null;
        try {
            // Obtenir le chemin de la ressource
            File imageFile = new File("img/"+filename);
            InputStream inputStream = new FileInputStream(imageFile);
            image = new ImageIcon(ImageIO.read(inputStream));
        }catch(Exception e){
            e.printStackTrace();
        }
        return image;
    }

    public void update_pont(Terrain t) {  //fonction modélisant l'écroulement du pont //on change quand on en a besoin rather vérification  
        for (int i = 0; i < 19; i++) { // accès privé mais besoin de l'utiliser
            if (!(t.getTabPontCase(i))) {  //la première case ayant la valeur true (pas encore écroulée)
                String nomImage = "";
                int index = i + 1;
                if (i < 9) {
                    nomImage = "lave/lave_0" + index + ".gif";
                } else {
                    nomImage = "lave/lave_" + index + ".gif";
                }
                ClassLoader classLoader = getClass().getClassLoader();
                InputStream inputStream = classLoader.getResourceAsStream(nomImage);
                switch (i) {
                    case 0:
                        pont1.setIcon(this.loadImage(nomImage));
                        break;
                    case 1:
                        pont2.setIcon(this.loadImage(nomImage));
                        break;
                    case 2:
                        pont3.setIcon(this.loadImage(nomImage));
                        break;
                    case 3:
                        pont4.setIcon(this.loadImage(nomImage));
                        break;
                    case 4:
                        pont5.setIcon(this.loadImage(nomImage));
                        break;
                    case 5:
                        pont6.setIcon(this.loadImage(nomImage));
                        break;
                    case 6:
                        pont7.setIcon(this.loadImage(nomImage));
                        break;
                    case 7:
                        pont8.setIcon(this.loadImage(nomImage));
                        break;
                    case 8:
                        pont9.setIcon(this.loadImage(nomImage));
                        break;
                    case 9:
                        pont10.setIcon(this.loadImage(nomImage));
                        break;
                    case 10:
                        pont11.setIcon(this.loadImage(nomImage));
                        break;
                    case 11:
                        pont12.setIcon(this.loadImage(nomImage));
                        break;
                    case 12:
                        pont13.setIcon(this.loadImage(nomImage));
                        break;
                    case 13:
                        pont14.setIcon(this.loadImage(nomImage));
                        break;
                    case 14:
                        pont15.setIcon(this.loadImage(nomImage));
                        break;
                    case 15:
                        pont16.setIcon(this.loadImage(nomImage));
                        break;
                    case 16:
                        pont17.setIcon(this.loadImage(nomImage));
                        break;
                    case 17:
                        pont18.setIcon(this.loadImage(nomImage));
                        break;
                    case 18:
                        pont19.setIcon(this.loadImage(nomImage));
                        break;
                }
                //On remplace la case par l'image de lave // écrouke pont on change directement l'image à la place de vérifier

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        historique = new javax.swing.JTextField();
        pont6 = new javax.swing.JLabel();
        pont13 = new javax.swing.JLabel();
        pont15 = new javax.swing.JLabel();
        pont14 = new javax.swing.JLabel();
        pont16 = new javax.swing.JLabel();
        pont11 = new javax.swing.JLabel();
        pont17 = new javax.swing.JLabel();
        pont12 = new javax.swing.JLabel();
        pont18 = new javax.swing.JLabel();
        pont3 = new javax.swing.JLabel();
        pont1 = new javax.swing.JLabel();
        pont2 = new javax.swing.JLabel();
        pont5 = new javax.swing.JLabel();
        pont9 = new javax.swing.JLabel();
        pont10 = new javax.swing.JLabel();
        pont8 = new javax.swing.JLabel();
        pont4 = new javax.swing.JLabel();
        pont7 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        sorcier_rouge = new javax.swing.JLabel();
        sorcier_vert = new javax.swing.JLabel();
        mur_feu = new javax.swing.JLabel();
        feu_droite = new javax.swing.JLabel();
        feu_gauche = new javax.swing.JLabel();
        pont19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        new_game = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup.getContentPane());
        popup.getContentPane().setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shazamm");

        historique.setBackground(new java.awt.Color(204, 102, 255));
        historique.setText("Historique");

        pont6.setText("jLabel1");

        pont13.setText("jLabel1");

        pont15.setText("jLabel1");

        pont14.setText("jLabel1");

        pont16.setText("jLabel1");

        pont11.setText("jLabel1");

        pont17.setText("jLabel1");

        pont12.setText("jLabel1");

        pont18.setText("jLabel1");

        pont3.setText("jLabel1");

        pont1.setText("jLabel1");

        pont2.setText("jLabel1");

        pont5.setText("jLabel1");

        pont9.setText("jLabel1");

        pont10.setText("jLabel1");

        pont8.setText("jLabel1");

        pont4.setText("jLabel1");

        pont7.setText("jLabel1");

        start.setText("Start");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        sorcier_rouge.setText("Sorcier rouge");

        sorcier_vert.setText("Sorcier vert");

        mur_feu.setText("Mur de feu");

        feu_droite.setText("Feu droite");

        feu_gauche.setText("Feu gauche");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historique, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(start))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(sorcier_rouge))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pont1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pont2)
                                .addGap(18, 18, 18)
                                .addComponent(pont3)
                                .addGap(18, 18, 18)
                                .addComponent(pont4)
                                .addGap(18, 18, 18)
                                .addComponent(pont5)
                                .addGap(18, 18, 18)
                                .addComponent(pont6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pont7)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feu_gauche)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pont8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pont9)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pont10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mur_feu))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pont12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feu_droite)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pont11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pont13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(pont14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pont16)
                                .addGap(18, 18, 18)
                                .addComponent(pont15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pont17)
                                .addGap(18, 18, 18)
                                .addComponent(pont18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sorcier_vert)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(historique))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(start)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sorcier_rouge, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(feu_gauche, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sorcier_vert, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mur_feu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pont1)
                                    .addComponent(pont2)
                                    .addComponent(pont3)
                                    .addComponent(pont4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pont5)
                                    .addComponent(pont6)
                                    .addComponent(pont7)
                                    .addComponent(pont8)
                                    .addComponent(pont9)
                                    .addComponent(pont10)
                                    .addComponent(pont11)
                                    .addComponent(pont12)
                                    .addComponent(pont13)
                                    .addComponent(pont14)
                                    .addComponent(pont16)
                                    .addComponent(pont15)
                                    .addComponent(pont17)
                                    .addComponent(pont18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(feu_droite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3572, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pont19.setText("jLabel1");

        jMenu1.setText("File");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        new_game.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        new_game.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        new_game.setText("New game");
        jMenu1.add(new_game);

        quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quit.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(quit);

        jMenuBar1.add(jMenu1);

        help.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        about.setText("About");
        help.add(about);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pont19)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(pont19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        //Implantation d'images des 19 morceaux du pont non dynamique
        for (int i = 0; i < 19; i++) {
            int index = i + 1;
            String nomImage = "";
            if (i < 9) {
                nomImage = "pont/pont_0" + index + ".gif";
            } else {
                nomImage = "pont/pont_" + index + ".gif";
            }
            ClassLoader classLoader = getClass().getClassLoader();
            InputStream inputStream = classLoader.getResourceAsStream(nomImage);
            switch (i) {
                case 0:
                    pont1.setIcon(this.loadImage(nomImage));
                    break;
                case 1:
                    pont2.setIcon(this.loadImage(nomImage));
                    break;
                case 2:
                    pont3.setIcon(this.loadImage(nomImage));
                    break;
                case 3:
                    pont4.setIcon(this.loadImage(nomImage));
                    break;
                case 4:
                    pont5.setIcon(this.loadImage(nomImage));
                    break;
                case 5:
                    pont6.setIcon(this.loadImage(nomImage));
                    break;
                case 6:
                    pont7.setIcon(this.loadImage(nomImage));
                    break;
                case 7:
                    pont8.setIcon(this.loadImage(nomImage));
                    break;
                case 8:
                    pont9.setIcon(this.loadImage(nomImage));
                    break;
                case 9:
                    pont10.setIcon(this.loadImage(nomImage));
                    break;
                case 10:
                    pont11.setIcon(this.loadImage(nomImage));
                    break;
                case 11:
                    pont12.setIcon(this.loadImage(nomImage));
                    break;
                case 12:
                    pont13.setIcon(this.loadImage(nomImage));
                    break;
                case 13:
                    pont14.setIcon(this.loadImage(nomImage));
                    break;
                case 14:
                    pont15.setIcon(this.loadImage(nomImage));
                    break;
                case 15:
                    pont16.setIcon(this.loadImage(nomImage));
                    break;
                case 16:
                    pont17.setIcon(this.loadImage(nomImage));
                    break;
                case 17:
                    pont18.setIcon(this.loadImage(nomImage));
                    break;
                case 18:
                    pont19.setIcon(this.loadImage(nomImage));
                    break;
            }
        }
        
        sorcier_rouge.setIcon(this.loadImage("perso/rouge.gif"));

        
    }//GEN-LAST:event_startMouseClicked

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        boolean b = popup.requestFocusInWindow();
        // demande le focus sur la nouvelle fenêtre
        popup.pack();
        // redimensionne la fenêtre popup
        popup.setVisible(true);
        // rend la fenêtre visible

    }//GEN-LAST:event_startActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JLabel feu_droite;
    private javax.swing.JLabel feu_gauche;
    private javax.swing.JMenu help;
    private javax.swing.JTextField historique;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mur_feu;
    private javax.swing.JMenuItem new_game;
    private javax.swing.JLabel pont1;
    private javax.swing.JLabel pont10;
    private javax.swing.JLabel pont11;
    private javax.swing.JLabel pont12;
    private javax.swing.JLabel pont13;
    private javax.swing.JLabel pont14;
    private javax.swing.JLabel pont15;
    private javax.swing.JLabel pont16;
    private javax.swing.JLabel pont17;
    private javax.swing.JLabel pont18;
    private javax.swing.JLabel pont19;
    private javax.swing.JLabel pont2;
    private javax.swing.JLabel pont3;
    private javax.swing.JLabel pont4;
    private javax.swing.JLabel pont5;
    private javax.swing.JLabel pont6;
    private javax.swing.JLabel pont7;
    private javax.swing.JLabel pont8;
    private javax.swing.JLabel pont9;
    private javax.swing.JFrame popup;
    private javax.swing.JMenuItem quit;
    private javax.swing.JLabel sorcier_rouge;
    private javax.swing.JLabel sorcier_vert;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
